### ISSUE TITLE
Update preact dependency

### ISSUE THREAD

**Issue by caesarsol** [laurencedorman/preact-classless-component#4]
Hello, could you update the preact version dependency? The latest is `7.2.0` and you have `6.2.0`.

I've not verified, but since almost no API is used in this package it should remain compatible...

Thanks!

**Comment by laurencedorman** [comment]
If you would like to submit a pull request I would be happy to merge.

Laurence Dorman

**Comment by caesarsol** [comment]
I'd like to, do you think it would be safe to include it as a versionless dependency?

**Comment by laurencedorman** [comment]
Sure why not, like you said this project doesn't use a lot of the API

**Comment by caesarsol** [comment]
I've looked into what Redux does with React:

```
  "peerDependencies": {
    "react": "^0.14.0 || ^15.0.0-0 || ^16.0.0-0",
    "redux": "^2.0.0 || ^3.0.0"
  },
```

We could do something similar.
